### PR TITLE
Improve data masking

### LINKED ISSUE #128: data masking: use `.data[["var"]]` instead of `.data$var`(same for `.env`)
more robust

### PR DESCRIPTION
**Pull request by jacobvjk**
closes #128

### CODE REVIEW

**Comment by jdhoffa** [comment]
looks robust to me

**Comment by jacobvjk** [comment]
actually just saw there ae some more cases in the tests... will tackle those too, just so it's done

**Review by cjyetman — APPROVED** [review]
wow, nice! ❤️

**Comment by jacobvjk** [comment]
@cjyetman I updated the test files too

**Pull request merged**
